// import 'dart:convert';

// import 'package:intl/intl.dart';
// import 'package:shared_preferences/shared_preferences.dart';
// import 'package:http/http.dart' as http;
// import '../Constant/Myconstant.dart';
// import '../Model/GetFinnancetrans_Model.dart';
// import '../Model/trans_re_bill_history_model.dart';
// import '../Model/trans_re_bill_model.dart';
// import '../PDF/PDF_Receipt/pdf_AC_his_statusbill.dart';
// import '../PDF/PDF_Temporary_Receipt/pdf_Temporary.dart';
// import '../PDF_TP2/PDF_Receipt_TP2/pdf_AC_his_statusbill_TP2.dart';
// import '../PDF_TP2/PDF_Temporary_Receipt_TP2/pdf_Temporar_TP2.dart';
// import '../PDF_TP3/PDF_Receipt_TP3/pdf_AC_his_statusbill_TP3.dart';
// import '../PDF_TP3/PDF_Temporary_Receipt_TP3/pdf_Temporar_TP3.dart';
// import '../PDF_TP4/PDF_Receipt_TP4/pdf_AC_his_statusbill_TP4.dart';
// import '../PDF_TP4/PDF_Temporary_Receipt_TP4/pdf_Temporar_TP4.dart';
// import '../PDF_TP5/PDF_Receipt_TP5/pdf_AC_his_statusbill_TP5.dart';
// import '../PDF_TP5/PDF_Temporary_Receipt_TP5/pdf_Temporar_TP5.dart';
// import '../PDF_TP6/PDF_Receipt_TP6/pdf_AC_his_statusbill_TP6.dart';
// import '../PDF_TP6/PDF_Temporary_Receipt_TP6/pdf_Temporar_TP6.dart';
// import '../PDF_TP7/PDF_Temporary_Receipt_TP7/pdf_Temporar_TP7.dart';
// import '../PDF_TP8/PDF_Temporary_Receipt_TP8/pdf_Temporar_TP8.dart';

// class ManTemporary_Receipt_PDF {
//   // --------------------------------> PDF รับชำระ และ PDF ประวัติบิล
//   static void ManTemporaryReceipt_PDF(
//       tableData001,
//       context,
//       select_page,
//       _TransReBillHistoryModels,
//       Get_Value_cid,
//       namenew,
//       sum_pvat,
//       sum_vat,
//       sum_wht,
//       sum_amt,
//       sum_disp,
//       sum_disamt,
//       total,
//       renTal_name,
//       Form_bussshop,
//       Form_address,
//       Form_tel,
//       Form_email,
//       Form_tax,
//       Form_nameshop,
//       bill_addr,
//       bill_email,
//       bill_tel,
//       bill_tax,
//       bill_name,
//       newValuePDFimg,
//       pamentpage,
//       paymentName1,
//       paymentName2,
//       Form_payment1_,
//       Form_payment2_,
//       numinvoice,
//       cFinn,
//       TitleType_Default_Receipt_Name,
//       tem_page_ser) async {
// ///////////////////------------------------------------->
//     if (tem_page_ser.toString() == '0' || tem_page_ser == null) {
//       Pdfgen_Temporary_receipt.exportPDF_Temporary_receipt(
//           tableData001,
//           context,
//           select_page,
//           _TransReBillHistoryModels,
//           Get_Value_cid,
//           namenew,
//           sum_pvat,
//           sum_vat,
//           sum_wht,
//           sum_amt,
//           sum_disp,
//           sum_disamt,
//           total,
//           renTal_name,
//           Form_bussshop,
//           Form_address,
//           Form_tel,
//           Form_email,
//           Form_tax,
//           Form_nameshop,
//           bill_addr,
//           bill_email,
//           bill_tel,
//           bill_tax,
//           bill_name,
//           newValuePDFimg,
//           pamentpage,
//           paymentName1,
//           paymentName2,
//           Form_payment1_,
//           Form_payment2_,
//           numinvoice,
//           cFinn,
//           TitleType_Default_Receipt_Name);
//     } else if (tem_page_ser.toString() == '1') {
//       Pdfgen_Temporary_receipt_TP2.exportPDF_Temporary_receipt_TP2(
//           tableData001,
//           context,
//           select_page,
//           _TransReBillHistoryModels,
//           Get_Value_cid,
//           namenew,
//           sum_pvat,
//           sum_vat,
//           sum_wht,
//           sum_amt,
//           sum_disp,
//           sum_disamt,
//           total,
//           renTal_name,
//           Form_bussshop,
//           Form_address,
//           Form_tel,
//           Form_email,
//           Form_tax,
//           Form_nameshop,
//           bill_addr,
//           bill_email,
//           bill_tel,
//           bill_tax,
//           bill_name,
//           newValuePDFimg,
//           pamentpage,
//           paymentName1,
//           paymentName2,
//           Form_payment1_,
//           Form_payment2_,
//           numinvoice,
//           cFinn,
//           TitleType_Default_Receipt_Name);
//     } else if (tem_page_ser.toString() == '2') {
//       Pdfgen_Temporary_receipt_TP3.exportPDF_Temporary_receipt_TP3(
//           tableData001,
//           context,
//           select_page,
//           _TransReBillHistoryModels,
//           Get_Value_cid,
//           namenew,
//           sum_pvat,
//           sum_vat,
//           sum_wht,
//           sum_amt,
//           sum_disp,
//           sum_disamt,
//           total,
//           renTal_name,
//           Form_bussshop,
//           Form_address,
//           Form_tel,
//           Form_email,
//           Form_tax,
//           Form_nameshop,
//           bill_addr,
//           bill_email,
//           bill_tel,
//           bill_tax,
//           bill_name,
//           newValuePDFimg,
//           pamentpage,
//           paymentName1,
//           paymentName2,
//           Form_payment1_,
//           Form_payment2_,
//           numinvoice,
//           cFinn,
//           TitleType_Default_Receipt_Name);
//     } else if (tem_page_ser.toString() == '3') {
//       Pdfgen_Temporary_receipt_TP4.exportPDF_Temporary_receipt_TP4(
//           tableData001,
//           context,
//           select_page,
//           _TransReBillHistoryModels,
//           Get_Value_cid,
//           namenew,
//           sum_pvat,
//           sum_vat,
//           sum_wht,
//           sum_amt,
//           sum_disp,
//           sum_disamt,
//           total,
//           renTal_name,
//           Form_bussshop,
//           Form_address,
//           Form_tel,
//           Form_email,
//           Form_tax,
//           Form_nameshop,
//           bill_addr,
//           bill_email,
//           bill_tel,
//           bill_tax,
//           bill_name,
//           newValuePDFimg,
//           pamentpage,
//           paymentName1,
//           paymentName2,
//           Form_payment1_,
//           Form_payment2_,
//           numinvoice,
//           cFinn,
//           TitleType_Default_Receipt_Name);
//     } else if (tem_page_ser.toString() == '4') {
//       Pdfgen_Temporary_receipt_TP5.exportPDF_Temporary_receipt_TP5(
//           tableData001,
//           context,
//           select_page,
//           _TransReBillHistoryModels,
//           Get_Value_cid,
//           namenew,
//           sum_pvat,
//           sum_vat,
//           sum_wht,
//           sum_amt,
//           sum_disp,
//           sum_disamt,
//           total,
//           renTal_name,
//           Form_bussshop,
//           Form_address,
//           Form_tel,
//           Form_email,
//           Form_tax,
//           Form_nameshop,
//           bill_addr,
//           bill_email,
//           bill_tel,
//           bill_tax,
//           bill_name,
//           newValuePDFimg,
//           pamentpage,
//           paymentName1,
//           paymentName2,
//           Form_payment1_,
//           Form_payment2_,
//           numinvoice,
//           cFinn,
//           TitleType_Default_Receipt_Name);
//     } else if (tem_page_ser.toString() == '5') {
//       Pdfgen_Temporary_receipt_TP6.exportPDF_Temporary_receipt_TP6(
//           tableData001,
//           context,
//           select_page,
//           _TransReBillHistoryModels,
//           Get_Value_cid,
//           namenew,
//           sum_pvat,
//           sum_vat,
//           sum_wht,
//           sum_amt,
//           sum_disp,
//           sum_disamt,
//           total,
//           renTal_name,
//           Form_bussshop,
//           Form_address,
//           Form_tel,
//           Form_email,
//           Form_tax,
//           Form_nameshop,
//           bill_addr,
//           bill_email,
//           bill_tel,
//           bill_tax,
//           bill_name,
//           newValuePDFimg,
//           pamentpage,
//           paymentName1,
//           paymentName2,
//           Form_payment1_,
//           Form_payment2_,
//           numinvoice,
//           cFinn,
//           TitleType_Default_Receipt_Name);
//     } else if (tem_page_ser.toString() == '6') {
//       Pdfgen_Temporary_receipt_TP7.exportPDF_Temporary_receipt_TP7(
//           tableData001,
//           context,
//           select_page,
//           _TransReBillHistoryModels,
//           Get_Value_cid,
//           namenew,
//           sum_pvat,
//           sum_vat,
//           sum_wht,
//           sum_amt,
//           sum_disp,
//           sum_disamt,
//           total,
//           renTal_name,
//           Form_bussshop,
//           Form_address,
//           Form_tel,
//           Form_email,
//           Form_tax,
//           Form_nameshop,
//           bill_addr,
//           bill_email,
//           bill_tel,
//           bill_tax,
//           bill_name,
//           newValuePDFimg,
//           pamentpage,
//           paymentName1,
//           paymentName2,
//           Form_payment1_,
//           Form_payment2_,
//           numinvoice,
//           cFinn,
//           TitleType_Default_Receipt_Name);
//     } else if (tem_page_ser.toString() == '7') {
//       Pdfgen_Temporary_receipt_TP8.exportPDF_Temporary_receipt_TP8(
//           tableData001,
//           context,
//           select_page,
//           _TransReBillHistoryModels,
//           Get_Value_cid,
//           namenew,
//           sum_pvat,
//           sum_vat,
//           sum_wht,
//           sum_amt,
//           sum_disp,
//           sum_disamt,
//           total,
//           renTal_name,
//           Form_bussshop,
//           Form_address,
//           Form_tel,
//           Form_email,
//           Form_tax,
//           Form_nameshop,
//           bill_addr,
//           bill_email,
//           bill_tel,
//           bill_tax,
//           bill_name,
//           newValuePDFimg,
//           pamentpage,
//           paymentName1,
//           paymentName2,
//           Form_payment1_,
//           Form_payment2_,
//           numinvoice,
//           cFinn,
//           TitleType_Default_Receipt_Name);
//     }
//   }
// }
